server:
 port: 8088

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
    initialization-mode: always
    
  h2:
    console.enabled: true